//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("TygModel", "FK_书名表_分类表", "分类表", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BaiduMapConvertManager.分类表), "书名表", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BaiduMapConvertManager.书名表), true)]
[assembly: EdmRelationshipAttribute("TygModel", "FK_文章表_书名表", "书名表", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BaiduMapConvertManager.书名表), "文章表", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BaiduMapConvertManager.文章表), true)]

#endregion

namespace BaiduMapConvertManager
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Entities”部分中的连接字符串初始化新 Entities 对象。
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<分类表> 分类表
        {
            get
            {
                if ((_分类表 == null))
                {
                    _分类表 = base.CreateObjectSet<分类表>("分类表");
                }
                return _分类表;
            }
        }
        private ObjectSet<分类表> _分类表;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<书名表> 书名表
        {
            get
            {
                if ((_书名表 == null))
                {
                    _书名表 = base.CreateObjectSet<书名表>("书名表");
                }
                return _书名表;
            }
        }
        private ObjectSet<书名表> _书名表;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<文章表> 文章表
        {
            get
            {
                if ((_文章表 == null))
                {
                    _文章表 = base.CreateObjectSet<文章表>("文章表");
                }
                return _文章表;
            }
        }
        private ObjectSet<文章表> _文章表;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 分类表 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo分类表(分类表 分类表)
        {
            base.AddObject("分类表", 分类表);
        }
    
        /// <summary>
        /// 用于向 书名表 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo书名表(书名表 书名表)
        {
            base.AddObject("书名表", 书名表);
        }
    
        /// <summary>
        /// 用于向 文章表 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo文章表(文章表 文章表)
        {
            base.AddObject("文章表", 文章表);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TygModel", Name="分类表")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 分类表 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 分类表 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="分类名称">分类名称 属性的初始值。</param>
        /// <param name="通用分类">通用分类 属性的初始值。</param>
        /// <param name="分类说明">分类说明 属性的初始值。</param>
        /// <param name="分类标识">分类标识 属性的初始值。</param>
        public static 分类表 Create分类表(global::System.Decimal id, global::System.String 分类名称, global::System.String 通用分类, global::System.String 分类说明, global::System.String 分类标识)
        {
            分类表 分类表 = new 分类表();
            分类表.ID = id;
            分类表.分类名称 = 分类名称;
            分类表.通用分类 = 通用分类;
            分类表.分类说明 = 分类说明;
            分类表.分类标识 = 分类标识;
            return 分类表;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 分类名称
        {
            get
            {
                return _分类名称;
            }
            set
            {
                On分类名称Changing(value);
                ReportPropertyChanging("分类名称");
                _分类名称 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("分类名称");
                On分类名称Changed();
            }
        }
        private global::System.String _分类名称;
        partial void On分类名称Changing(global::System.String value);
        partial void On分类名称Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 通用分类
        {
            get
            {
                return _通用分类;
            }
            set
            {
                On通用分类Changing(value);
                ReportPropertyChanging("通用分类");
                _通用分类 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("通用分类");
                On通用分类Changed();
            }
        }
        private global::System.String _通用分类;
        partial void On通用分类Changing(global::System.String value);
        partial void On通用分类Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 分类说明
        {
            get
            {
                return _分类说明;
            }
            set
            {
                On分类说明Changing(value);
                ReportPropertyChanging("分类说明");
                _分类说明 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("分类说明");
                On分类说明Changed();
            }
        }
        private global::System.String _分类说明;
        partial void On分类说明Changing(global::System.String value);
        partial void On分类说明Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 分类标识
        {
            get
            {
                return _分类标识;
            }
            set
            {
                if (_分类标识 != value)
                {
                    On分类标识Changing(value);
                    ReportPropertyChanging("分类标识");
                    _分类标识 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("分类标识");
                    On分类标识Changed();
                }
            }
        }
        private global::System.String _分类标识;
        partial void On分类标识Changing(global::System.String value);
        partial void On分类标识Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 通用分类1
        {
            get
            {
                return _通用分类1;
            }
            set
            {
                On通用分类1Changing(value);
                ReportPropertyChanging("通用分类1");
                _通用分类1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("通用分类1");
                On通用分类1Changed();
            }
        }
        private global::System.String _通用分类1;
        partial void On通用分类1Changing(global::System.String value);
        partial void On通用分类1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 备注
        {
            get
            {
                return _备注;
            }
            set
            {
                On备注Changing(value);
                ReportPropertyChanging("备注");
                _备注 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("备注");
                On备注Changed();
            }
        }
        private global::System.String _备注;
        partial void On备注Changing(global::System.String value);
        partial void On备注Changed();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TygModel", "FK_书名表_分类表", "书名表")]
        public EntityCollection<书名表> 书名表
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<书名表>("TygModel.FK_书名表_分类表", "书名表");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<书名表>("TygModel.FK_书名表_分类表", "书名表", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TygModel", Name="书名表")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 书名表 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 书名表 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="gUID">GUID 属性的初始值。</param>
        /// <param name="书名">书名 属性的初始值。</param>
        /// <param name="分类标识">分类标识 属性的初始值。</param>
        /// <param name="分类表ID">分类表ID 属性的初始值。</param>
        /// <param name="说明">说明 属性的初始值。</param>
        /// <param name="作者名称">作者名称 属性的初始值。</param>
        /// <param name="创建时间">创建时间 属性的初始值。</param>
        /// <param name="周点击">周点击 属性的初始值。</param>
        /// <param name="总点击">总点击 属性的初始值。</param>
        /// <param name="周鲜花">周鲜花 属性的初始值。</param>
        /// <param name="总鲜花">总鲜花 属性的初始值。</param>
        /// <param name="免费">免费 属性的初始值。</param>
        /// <param name="完本">完本 属性的初始值。</param>
        public static 书名表 Create书名表(global::System.Decimal id, global::System.Guid gUID, global::System.String 书名, global::System.String 分类标识, global::System.Decimal 分类表ID, global::System.String 说明, global::System.String 作者名称, global::System.DateTime 创建时间, global::System.Decimal 周点击, global::System.Decimal 总点击, global::System.Decimal 周鲜花, global::System.Decimal 总鲜花, global::System.Boolean 免费, global::System.Boolean 完本)
        {
            书名表 书名表 = new 书名表();
            书名表.ID = id;
            书名表.GUID = gUID;
            书名表.书名 = 书名;
            书名表.分类标识 = 分类标识;
            书名表.分类表ID = 分类表ID;
            书名表.说明 = 说明;
            书名表.作者名称 = 作者名称;
            书名表.创建时间 = 创建时间;
            书名表.周点击 = 周点击;
            书名表.总点击 = 总点击;
            书名表.周鲜花 = 周鲜花;
            书名表.总鲜花 = 总鲜花;
            书名表.免费 = 免费;
            书名表.完本 = 完本;
            return 书名表;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 书名
        {
            get
            {
                return _书名;
            }
            set
            {
                if (_书名 != value)
                {
                    On书名Changing(value);
                    ReportPropertyChanging("书名");
                    _书名 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("书名");
                    On书名Changed();
                }
            }
        }
        private global::System.String _书名;
        partial void On书名Changing(global::System.String value);
        partial void On书名Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 分类标识
        {
            get
            {
                return _分类标识;
            }
            set
            {
                if (_分类标识 != value)
                {
                    On分类标识Changing(value);
                    ReportPropertyChanging("分类标识");
                    _分类标识 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("分类标识");
                    On分类标识Changed();
                }
            }
        }
        private global::System.String _分类标识;
        partial void On分类标识Changing(global::System.String value);
        partial void On分类标识Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal 分类表ID
        {
            get
            {
                return _分类表ID;
            }
            set
            {
                On分类表IDChanging(value);
                ReportPropertyChanging("分类表ID");
                _分类表ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("分类表ID");
                On分类表IDChanged();
            }
        }
        private global::System.Decimal _分类表ID;
        partial void On分类表IDChanging(global::System.Decimal value);
        partial void On分类表IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 说明
        {
            get
            {
                return _说明;
            }
            set
            {
                On说明Changing(value);
                ReportPropertyChanging("说明");
                _说明 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("说明");
                On说明Changed();
            }
        }
        private global::System.String _说明;
        partial void On说明Changing(global::System.String value);
        partial void On说明Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 作者名称
        {
            get
            {
                return _作者名称;
            }
            set
            {
                On作者名称Changing(value);
                ReportPropertyChanging("作者名称");
                _作者名称 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("作者名称");
                On作者名称Changed();
            }
        }
        private global::System.String _作者名称;
        partial void On作者名称Changing(global::System.String value);
        partial void On作者名称Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime 创建时间
        {
            get
            {
                return _创建时间;
            }
            set
            {
                On创建时间Changing(value);
                ReportPropertyChanging("创建时间");
                _创建时间 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("创建时间");
                On创建时间Changed();
            }
        }
        private global::System.DateTime _创建时间;
        partial void On创建时间Changing(global::System.DateTime value);
        partial void On创建时间Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 配图
        {
            get
            {
                return _配图;
            }
            set
            {
                On配图Changing(value);
                ReportPropertyChanging("配图");
                _配图 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("配图");
                On配图Changed();
            }
        }
        private global::System.String _配图;
        partial void On配图Changing(global::System.String value);
        partial void On配图Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal 周点击
        {
            get
            {
                return _周点击;
            }
            set
            {
                On周点击Changing(value);
                ReportPropertyChanging("周点击");
                _周点击 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("周点击");
                On周点击Changed();
            }
        }
        private global::System.Decimal _周点击;
        partial void On周点击Changing(global::System.Decimal value);
        partial void On周点击Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal 总点击
        {
            get
            {
                return _总点击;
            }
            set
            {
                On总点击Changing(value);
                ReportPropertyChanging("总点击");
                _总点击 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("总点击");
                On总点击Changed();
            }
        }
        private global::System.Decimal _总点击;
        partial void On总点击Changing(global::System.Decimal value);
        partial void On总点击Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal 周鲜花
        {
            get
            {
                return _周鲜花;
            }
            set
            {
                On周鲜花Changing(value);
                ReportPropertyChanging("周鲜花");
                _周鲜花 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("周鲜花");
                On周鲜花Changed();
            }
        }
        private global::System.Decimal _周鲜花;
        partial void On周鲜花Changing(global::System.Decimal value);
        partial void On周鲜花Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal 总鲜花
        {
            get
            {
                return _总鲜花;
            }
            set
            {
                On总鲜花Changing(value);
                ReportPropertyChanging("总鲜花");
                _总鲜花 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("总鲜花");
                On总鲜花Changed();
            }
        }
        private global::System.Decimal _总鲜花;
        partial void On总鲜花Changing(global::System.Decimal value);
        partial void On总鲜花Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean 免费
        {
            get
            {
                return _免费;
            }
            set
            {
                On免费Changing(value);
                ReportPropertyChanging("免费");
                _免费 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("免费");
                On免费Changed();
            }
        }
        private global::System.Boolean _免费;
        partial void On免费Changing(global::System.Boolean value);
        partial void On免费Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean 完本
        {
            get
            {
                return _完本;
            }
            set
            {
                On完本Changing(value);
                ReportPropertyChanging("完本");
                _完本 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("完本");
                On完本Changed();
            }
        }
        private global::System.Boolean _完本;
        partial void On完本Changing(global::System.Boolean value);
        partial void On完本Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> 最后更新时间
        {
            get
            {
                return _最后更新时间;
            }
            set
            {
                On最后更新时间Changing(value);
                ReportPropertyChanging("最后更新时间");
                _最后更新时间 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("最后更新时间");
                On最后更新时间Changed();
            }
        }
        private Nullable<global::System.DateTime> _最后更新时间;
        partial void On最后更新时间Changing(Nullable<global::System.DateTime> value);
        partial void On最后更新时间Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 最新章节
        {
            get
            {
                return _最新章节;
            }
            set
            {
                On最新章节Changing(value);
                ReportPropertyChanging("最新章节");
                _最新章节 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("最新章节");
                On最新章节Changed();
            }
        }
        private global::System.String _最新章节;
        partial void On最新章节Changing(global::System.String value);
        partial void On最新章节Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL1
        {
            get
            {
                return _采集用的URL1;
            }
            set
            {
                On采集用的URL1Changing(value);
                ReportPropertyChanging("采集用的URL1");
                _采集用的URL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL1");
                On采集用的URL1Changed();
            }
        }
        private global::System.String _采集用的URL1;
        partial void On采集用的URL1Changing(global::System.String value);
        partial void On采集用的URL1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL2
        {
            get
            {
                return _采集用的URL2;
            }
            set
            {
                On采集用的URL2Changing(value);
                ReportPropertyChanging("采集用的URL2");
                _采集用的URL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL2");
                On采集用的URL2Changed();
            }
        }
        private global::System.String _采集用的URL2;
        partial void On采集用的URL2Changing(global::System.String value);
        partial void On采集用的URL2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL3
        {
            get
            {
                return _采集用的URL3;
            }
            set
            {
                On采集用的URL3Changing(value);
                ReportPropertyChanging("采集用的URL3");
                _采集用的URL3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL3");
                On采集用的URL3Changed();
            }
        }
        private global::System.String _采集用的URL3;
        partial void On采集用的URL3Changing(global::System.String value);
        partial void On采集用的URL3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL4
        {
            get
            {
                return _采集用的URL4;
            }
            set
            {
                On采集用的URL4Changing(value);
                ReportPropertyChanging("采集用的URL4");
                _采集用的URL4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL4");
                On采集用的URL4Changed();
            }
        }
        private global::System.String _采集用的URL4;
        partial void On采集用的URL4Changing(global::System.String value);
        partial void On采集用的URL4Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL5
        {
            get
            {
                return _采集用的URL5;
            }
            set
            {
                On采集用的URL5Changing(value);
                ReportPropertyChanging("采集用的URL5");
                _采集用的URL5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL5");
                On采集用的URL5Changed();
            }
        }
        private global::System.String _采集用的URL5;
        partial void On采集用的URL5Changing(global::System.String value);
        partial void On采集用的URL5Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL6
        {
            get
            {
                return _采集用的URL6;
            }
            set
            {
                On采集用的URL6Changing(value);
                ReportPropertyChanging("采集用的URL6");
                _采集用的URL6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL6");
                On采集用的URL6Changed();
            }
        }
        private global::System.String _采集用的URL6;
        partial void On采集用的URL6Changing(global::System.String value);
        partial void On采集用的URL6Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL7
        {
            get
            {
                return _采集用的URL7;
            }
            set
            {
                On采集用的URL7Changing(value);
                ReportPropertyChanging("采集用的URL7");
                _采集用的URL7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL7");
                On采集用的URL7Changed();
            }
        }
        private global::System.String _采集用的URL7;
        partial void On采集用的URL7Changing(global::System.String value);
        partial void On采集用的URL7Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL8
        {
            get
            {
                return _采集用的URL8;
            }
            set
            {
                On采集用的URL8Changing(value);
                ReportPropertyChanging("采集用的URL8");
                _采集用的URL8 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL8");
                On采集用的URL8Changed();
            }
        }
        private global::System.String _采集用的URL8;
        partial void On采集用的URL8Changing(global::System.String value);
        partial void On采集用的URL8Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL9
        {
            get
            {
                return _采集用的URL9;
            }
            set
            {
                On采集用的URL9Changing(value);
                ReportPropertyChanging("采集用的URL9");
                _采集用的URL9 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL9");
                On采集用的URL9Changed();
            }
        }
        private global::System.String _采集用的URL9;
        partial void On采集用的URL9Changing(global::System.String value);
        partial void On采集用的URL9Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL10
        {
            get
            {
                return _采集用的URL10;
            }
            set
            {
                On采集用的URL10Changing(value);
                ReportPropertyChanging("采集用的URL10");
                _采集用的URL10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL10");
                On采集用的URL10Changed();
            }
        }
        private global::System.String _采集用的URL10;
        partial void On采集用的URL10Changing(global::System.String value);
        partial void On采集用的URL10Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 首发地址
        {
            get
            {
                return _首发地址;
            }
            set
            {
                On首发地址Changing(value);
                ReportPropertyChanging("首发地址");
                _首发地址 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("首发地址");
                On首发地址Changed();
            }
        }
        private global::System.String _首发地址;
        partial void On首发地址Changing(global::System.String value);
        partial void On首发地址Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> 包含有效章节
        {
            get
            {
                return _包含有效章节;
            }
            set
            {
                On包含有效章节Changing(value);
                ReportPropertyChanging("包含有效章节");
                _包含有效章节 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("包含有效章节");
                On包含有效章节Changed();
            }
        }
        private Nullable<global::System.Int32> _包含有效章节;
        partial void On包含有效章节Changing(Nullable<global::System.Int32> value);
        partial void On包含有效章节Changed();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TygModel", "FK_书名表_分类表", "分类表")]
        public 分类表 分类表
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<分类表>("TygModel.FK_书名表_分类表", "分类表").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<分类表>("TygModel.FK_书名表_分类表", "分类表").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<分类表> 分类表Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<分类表>("TygModel.FK_书名表_分类表", "分类表");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<分类表>("TygModel.FK_书名表_分类表", "分类表", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TygModel", "FK_文章表_书名表", "文章表")]
        public EntityCollection<文章表> 文章表
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<文章表>("TygModel.FK_文章表_书名表", "文章表");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<文章表>("TygModel.FK_文章表_书名表", "文章表", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TygModel", Name="文章表")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 文章表 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 文章表 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="书名">书名 属性的初始值。</param>
        /// <param name="gUID">GUID 属性的初始值。</param>
        /// <param name="分类名称">分类名称 属性的初始值。</param>
        /// <param name="分类标识">分类标识 属性的初始值。</param>
        /// <param name="章节名">章节名 属性的初始值。</param>
        /// <param name="内容">内容 属性的初始值。</param>
        /// <param name="本记录GUID">本记录GUID 属性的初始值。</param>
        /// <param name="创建时间">创建时间 属性的初始值。</param>
        public static 文章表 Create文章表(global::System.Decimal id, global::System.String 书名, global::System.Guid gUID, global::System.String 分类名称, global::System.String 分类标识, global::System.String 章节名, global::System.String 内容, global::System.Guid 本记录GUID, global::System.DateTime 创建时间)
        {
            文章表 文章表 = new 文章表();
            文章表.ID = id;
            文章表.书名 = 书名;
            文章表.GUID = gUID;
            文章表.分类名称 = 分类名称;
            文章表.分类标识 = 分类标识;
            文章表.章节名 = 章节名;
            文章表.内容 = 内容;
            文章表.本记录GUID = 本记录GUID;
            文章表.创建时间 = 创建时间;
            return 文章表;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 书名
        {
            get
            {
                return _书名;
            }
            set
            {
                if (_书名 != value)
                {
                    On书名Changing(value);
                    ReportPropertyChanging("书名");
                    _书名 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("书名");
                    On书名Changed();
                }
            }
        }
        private global::System.String _书名;
        partial void On书名Changing(global::System.String value);
        partial void On书名Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 分类名称
        {
            get
            {
                return _分类名称;
            }
            set
            {
                On分类名称Changing(value);
                ReportPropertyChanging("分类名称");
                _分类名称 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("分类名称");
                On分类名称Changed();
            }
        }
        private global::System.String _分类名称;
        partial void On分类名称Changing(global::System.String value);
        partial void On分类名称Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 分类标识
        {
            get
            {
                return _分类标识;
            }
            set
            {
                if (_分类标识 != value)
                {
                    On分类标识Changing(value);
                    ReportPropertyChanging("分类标识");
                    _分类标识 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("分类标识");
                    On分类标识Changed();
                }
            }
        }
        private global::System.String _分类标识;
        partial void On分类标识Changing(global::System.String value);
        partial void On分类标识Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 章节名
        {
            get
            {
                return _章节名;
            }
            set
            {
                On章节名Changing(value);
                ReportPropertyChanging("章节名");
                _章节名 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("章节名");
                On章节名Changed();
            }
        }
        private global::System.String _章节名;
        partial void On章节名Changing(global::System.String value);
        partial void On章节名Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 内容
        {
            get
            {
                return _内容;
            }
            set
            {
                On内容Changing(value);
                ReportPropertyChanging("内容");
                _内容 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("内容");
                On内容Changed();
            }
        }
        private global::System.String _内容;
        partial void On内容Changing(global::System.String value);
        partial void On内容Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> 总访问次数
        {
            get
            {
                return _总访问次数;
            }
            set
            {
                On总访问次数Changing(value);
                ReportPropertyChanging("总访问次数");
                _总访问次数 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("总访问次数");
                On总访问次数Changed();
            }
        }
        private Nullable<global::System.Decimal> _总访问次数;
        partial void On总访问次数Changing(Nullable<global::System.Decimal> value);
        partial void On总访问次数Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> 最后访问时间
        {
            get
            {
                return _最后访问时间;
            }
            set
            {
                On最后访问时间Changing(value);
                ReportPropertyChanging("最后访问时间");
                _最后访问时间 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("最后访问时间");
                On最后访问时间Changed();
            }
        }
        private Nullable<global::System.DateTime> _最后访问时间;
        partial void On最后访问时间Changing(Nullable<global::System.DateTime> value);
        partial void On最后访问时间Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> 上一章
        {
            get
            {
                return _上一章;
            }
            set
            {
                On上一章Changing(value);
                ReportPropertyChanging("上一章");
                _上一章 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("上一章");
                On上一章Changed();
            }
        }
        private Nullable<global::System.Guid> _上一章;
        partial void On上一章Changing(Nullable<global::System.Guid> value);
        partial void On上一章Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid 本记录GUID
        {
            get
            {
                return _本记录GUID;
            }
            set
            {
                if (_本记录GUID != value)
                {
                    On本记录GUIDChanging(value);
                    ReportPropertyChanging("本记录GUID");
                    _本记录GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("本记录GUID");
                    On本记录GUIDChanged();
                }
            }
        }
        private global::System.Guid _本记录GUID;
        partial void On本记录GUIDChanging(global::System.Guid value);
        partial void On本记录GUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> 下一章
        {
            get
            {
                return _下一章;
            }
            set
            {
                On下一章Changing(value);
                ReportPropertyChanging("下一章");
                _下一章 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("下一章");
                On下一章Changed();
            }
        }
        private Nullable<global::System.Guid> _下一章;
        partial void On下一章Changing(Nullable<global::System.Guid> value);
        partial void On下一章Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime 创建时间
        {
            get
            {
                return _创建时间;
            }
            set
            {
                On创建时间Changing(value);
                ReportPropertyChanging("创建时间");
                _创建时间 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("创建时间");
                On创建时间Changed();
            }
        }
        private global::System.DateTime _创建时间;
        partial void On创建时间Changing(global::System.DateTime value);
        partial void On创建时间Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL1
        {
            get
            {
                return _采集用的URL1;
            }
            set
            {
                On采集用的URL1Changing(value);
                ReportPropertyChanging("采集用的URL1");
                _采集用的URL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL1");
                On采集用的URL1Changed();
            }
        }
        private global::System.String _采集用的URL1;
        partial void On采集用的URL1Changing(global::System.String value);
        partial void On采集用的URL1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL2
        {
            get
            {
                return _采集用的URL2;
            }
            set
            {
                On采集用的URL2Changing(value);
                ReportPropertyChanging("采集用的URL2");
                _采集用的URL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL2");
                On采集用的URL2Changed();
            }
        }
        private global::System.String _采集用的URL2;
        partial void On采集用的URL2Changing(global::System.String value);
        partial void On采集用的URL2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL3
        {
            get
            {
                return _采集用的URL3;
            }
            set
            {
                On采集用的URL3Changing(value);
                ReportPropertyChanging("采集用的URL3");
                _采集用的URL3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL3");
                On采集用的URL3Changed();
            }
        }
        private global::System.String _采集用的URL3;
        partial void On采集用的URL3Changing(global::System.String value);
        partial void On采集用的URL3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL4
        {
            get
            {
                return _采集用的URL4;
            }
            set
            {
                On采集用的URL4Changing(value);
                ReportPropertyChanging("采集用的URL4");
                _采集用的URL4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL4");
                On采集用的URL4Changed();
            }
        }
        private global::System.String _采集用的URL4;
        partial void On采集用的URL4Changing(global::System.String value);
        partial void On采集用的URL4Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL5
        {
            get
            {
                return _采集用的URL5;
            }
            set
            {
                On采集用的URL5Changing(value);
                ReportPropertyChanging("采集用的URL5");
                _采集用的URL5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL5");
                On采集用的URL5Changed();
            }
        }
        private global::System.String _采集用的URL5;
        partial void On采集用的URL5Changing(global::System.String value);
        partial void On采集用的URL5Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL6
        {
            get
            {
                return _采集用的URL6;
            }
            set
            {
                On采集用的URL6Changing(value);
                ReportPropertyChanging("采集用的URL6");
                _采集用的URL6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL6");
                On采集用的URL6Changed();
            }
        }
        private global::System.String _采集用的URL6;
        partial void On采集用的URL6Changing(global::System.String value);
        partial void On采集用的URL6Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL7
        {
            get
            {
                return _采集用的URL7;
            }
            set
            {
                On采集用的URL7Changing(value);
                ReportPropertyChanging("采集用的URL7");
                _采集用的URL7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL7");
                On采集用的URL7Changed();
            }
        }
        private global::System.String _采集用的URL7;
        partial void On采集用的URL7Changing(global::System.String value);
        partial void On采集用的URL7Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL8
        {
            get
            {
                return _采集用的URL8;
            }
            set
            {
                On采集用的URL8Changing(value);
                ReportPropertyChanging("采集用的URL8");
                _采集用的URL8 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL8");
                On采集用的URL8Changed();
            }
        }
        private global::System.String _采集用的URL8;
        partial void On采集用的URL8Changing(global::System.String value);
        partial void On采集用的URL8Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL9
        {
            get
            {
                return _采集用的URL9;
            }
            set
            {
                On采集用的URL9Changing(value);
                ReportPropertyChanging("采集用的URL9");
                _采集用的URL9 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL9");
                On采集用的URL9Changed();
            }
        }
        private global::System.String _采集用的URL9;
        partial void On采集用的URL9Changing(global::System.String value);
        partial void On采集用的URL9Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String 采集用的URL10
        {
            get
            {
                return _采集用的URL10;
            }
            set
            {
                On采集用的URL10Changing(value);
                ReportPropertyChanging("采集用的URL10");
                _采集用的URL10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("采集用的URL10");
                On采集用的URL10Changed();
            }
        }
        private global::System.String _采集用的URL10;
        partial void On采集用的URL10Changing(global::System.String value);
        partial void On采集用的URL10Changed();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TygModel", "FK_文章表_书名表", "书名表")]
        public 书名表 书名表
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<书名表>("TygModel.FK_文章表_书名表", "书名表").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<书名表>("TygModel.FK_文章表_书名表", "书名表").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<书名表> 书名表Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<书名表>("TygModel.FK_文章表_书名表", "书名表");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<书名表>("TygModel.FK_文章表_书名表", "书名表", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
