using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;


using ICSharpCode.SharpZipLib.Zip;
using ICSharpCode.SharpZipLib.Checksums;
using System.IO;
using System.Text;

using Skybot.Tong.ZIP;
public partial class ZIP文件测试 : System.Web.UI.Page
{

    protected void Page_Load(object sender, EventArgs e)
    {
        //ZipFile(@"C:\Documents and Settings\zhouy\桌面\aa\新建 文本文档.txt", @"C:\Documents and Settings\zhouy\桌面\aa\0.zip", "");

        //for (int k = 0; k < 9999; k++)
        //{
        //    ZipFile(BufferArray);
        //}

        MemoryStream instream = new MemoryStream(BufferArray);
        MemoryStream outstream = new MemoryStream(BufferArray);





        System.IO.File.WriteAllBytes(@"C:\Documents and Settings\zhouy\桌面\aa\2.zip.xml", Compression.DeCompress(Compression.Compress(BufferArray)));




        System.IO.File.WriteAllBytes(@"C:\Documents and Settings\zhouy\桌面\aa\1.zip", ZipFile(BufferArray));

        制作一个Buffer压缩();


        压缩Buffer转换成正常的Buffer(制作一个Buffer压缩());

    }

    void 压缩Buffer转换成正常的Buffer(byte[] byteArray)
    {
        MemoryStream ms = new MemoryStream(byteArray);
        ZipInputStream a = new ZipInputStream(ms);


    }

    byte[] 制作一个Buffer压缩()
    {
        MemoryStream ms = new MemoryStream();



        ICSharpCode.SharpZipLib.Zip.Compression.Streams.DeflaterOutputStream s = new ICSharpCode.SharpZipLib.Zip.Compression.Streams.DeflaterOutputStream(
            ms, new ICSharpCode.SharpZipLib.Zip.Compression.Deflater(
                 ICSharpCode.SharpZipLib.Zip.Compression.Deflater.DEFAULT_COMPRESSION, true)
                );
        s.Write(BufferArray, 0, BufferArray.Length);
        s.Close();
        System.IO.File.WriteAllBytes(@"C:\Documents and Settings\zhouy\桌面\aa\0.zip", ms.GetBuffer());

        return ms.GetBuffer();
    }


    /// 压缩文件
    /// 
    /// 要进行压缩的文件名
    /// 压缩后生成的压缩文件名
    /// 
    private static byte[] ZipFile(byte[] BufferToZip)
    {
        MemoryStream memoryStream = new MemoryStream();
        ZipOutputStream ZipStream = null;
        ZipEntry ZipEntry = null;
        ZipStream = new ZipOutputStream(memoryStream);
        ZipEntry = new ZipEntry("1.txt");
        ZipStream.PutNextEntry(ZipEntry);
        ZipStream.SetLevel(1);
        ZipStream.Write(BufferArray, 0, BufferArray.Length);
        if (ZipEntry != null)
        {
            ZipEntry = null;
        }
        if (ZipStream != null)
        {
            ZipStream.Finish();
            ZipStream.Close();
        }

        return memoryStream.GetBuffer();

    }






    #region MyRegion
    static byte[] BufferArray = System.Text.UTF8Encoding.UTF8.GetBytes(@"<?xml version=""1.0"" encoding=""utf-8""?>
<protocol>
  <head>
    <flag>ICENTER</flag>
    <version>0</version>
    <message>293</message>
    <session>2</session>
    <workflow>5547659893135040483</workflow>
    <userid>1010</userid>
  </head>
  <body>
    <RetDataCrud>
      <ret>
        <iValue>0</iValue>
        <description />
      </ret>
      <iCount>109</iCount>
      <entity>
        <szSourceName>VIEW_SPEED_OVER_BODY</szSourceName>
        <szReporthead />
        <szReportbody>&lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;1&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D079&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;周东路年家浜东路&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;6&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;50&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:12:0&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:12:00&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:12:00&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:12:00到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;3&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;花木&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;45&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;4&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;陈家桥&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;48&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;5&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D078&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;康桥文化中心&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;13&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;6&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D078&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;康桥文化中心&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;13&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;7&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D072&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;长征&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;17&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;8&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D072&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;陈家桥&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;20&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;9&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:26&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:26&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:26&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:26到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;10&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:26&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:26&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:26&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:26到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;11&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:26&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:26&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:26&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:26到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;12&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:26&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:26&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:26&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:26到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;13&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:27&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:27&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:27&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:27到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;14&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:27&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:27&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:27&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:27到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;15&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:27&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:27&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:27&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:27到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;16&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:27&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:27&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:27&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:27到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;17&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:27&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:27&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:27&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:27到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;18&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:27&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:27&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:27&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:27到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;19&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:28&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:28&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:28&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:28到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;20&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:28&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:28&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:28&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:28到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;21&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:28&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:28&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:28&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:28到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;22&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:28&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:28&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:28&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:28到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;23&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:28&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:28&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:28&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:28到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;24&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:29&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:29&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:29&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:29到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;25&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:29&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:29&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:29&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:29到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;26&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:29&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:29&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:29&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:29到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;27&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:29&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:29&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:29&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:29到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;28&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;29&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;30&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;31&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;32&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;33&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;34&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;35&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;36&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;37&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;38&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;39&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:45&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:45&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:45&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:45到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;40&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:6&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:06&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:06&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:06到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;41&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:6&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:06&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:06&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:06到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;42&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:6&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:06&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:06&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:06到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;43&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:6&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:06&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:06&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:06到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;44&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:6&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:06&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:06&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:06到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;45&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:6&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:06&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:06&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:06到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;46&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:6&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:06&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D196&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;易初莲花&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:06&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:06到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;43&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;47&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:58&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:58&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D067&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;长征&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:58&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:58到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;17&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;48&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:57&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:57&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D067&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;长征&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:57&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:57到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;17&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;49&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:11:59&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:11:59&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D067&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;长征&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:11:59&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:11:59到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;17&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
   &lt;VIEW_SPEED_OVER_BODY&gt;
      &lt;RN&gt;2&lt;/RN&gt;
      &lt;T_DATE&gt;2009-10-08&lt;/T_DATE&gt;
      &lt;T_TIME&gt;10/8/2009 4:9:14&lt;/T_TIME&gt;
      &lt;T_CHECK_TIME&gt;04:09:14&lt;/T_CHECK_TIME&gt;
      &lt;F_OVER_SPEED&gt;85&lt;/F_OVER_SPEED&gt;
      &lt;UBI_ROUTE_ID&gt;451&lt;/UBI_ROUTE_ID&gt;
      &lt;SZ_ROUTE_NAME&gt;451路&lt;/SZ_ROUTE_NAME&gt;
      &lt;SZ_INTER_ID&gt;06S0D194&lt;/SZ_INTER_ID&gt;
      &lt;SZ_DRIVER_NAME&gt;  &lt;/SZ_DRIVER_NAME&gt;
      &lt;F_START_LONGITUDE&gt;0&lt;/F_START_LONGITUDE&gt;
      &lt;F_START_LATITUDE&gt;0&lt;/F_START_LATITUDE&gt;
      &lt;SZ_STATION_NAME&gt;花木&lt;/SZ_STATION_NAME&gt;
      &lt;SZ_DESCRIPTION&gt;  &lt;/SZ_DESCRIPTION&gt;
      &lt;SZ_REMARK&gt;超速&lt;/SZ_REMARK&gt;
      &lt;T_BEGIN&gt;04:09:14&lt;/T_BEGIN&gt;
      &lt;T_END&gt;00:00:00&lt;/T_END&gt;
      &lt;SZ_START_TIME_AND_END_TIME&gt;04:09:14到00:00:00&lt;/SZ_START_TIME_AND_END_TIME&gt;
      &lt;SZ_MAITTAIN_TIME&gt;0秒&lt;/SZ_MAITTAIN_TIME&gt;
      &lt;UI_STATION_INDEX&gt;45&lt;/UI_STATION_INDEX&gt;
   &lt;/VIEW_SPEED_OVER_BODY&gt;
</szReportbody>
      </entity>
    </RetDataCrud>
  </body>
</protocol>".ToCharArray());
    #endregion

}